In [2]:
import pandas as pd
data = pd.read_csv('http://raw.githubusercontent.com/ruslantur77/ml-journey/refs/heads/main/day_5/house_prices.csv')

In [3]:
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
19995    -119.86     34.42                23.0       1450.0           642.0   
19996    -118.14     34.06                27.0       5257.0          1082.0   
19997    -119.70     36.30                10.0        956.0           201.0   
19998    -117.12     34.10                40.0         96.0            14.0   
19999    -119.63     34.42                42.0       1765.0           263.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
19995      1258.0       607.0         1.1790            225000.0  
19996      3496.0      1036.0         3.3906            237200.0  
19997       693.0       220.0         2.2895             62000.0  
19998        46.0        14.0         3.2708            162500.0  
19999       753.0       260.0         8.5608            500001.0  

[20000 rows x 9 columns]

In [4]:
unscaled_X = data.drop('median_house_value', axis=1)
unscaled_y = data['median_house_value']

In [5]:
unscaled_X

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
19995    -119.86     34.42                23.0       1450.0           642.0   
19996    -118.14     34.06                27.0       5257.0          1082.0   
19997    -119.70     36.30                10.0        956.0           201.0   
19998    -117.12     34.10                40.0         96.0            14.0   
19999    -119.63     34.42                42.0       1765.0           263.0   

       population  households  median_income  
0          1015.0       472.0         1.4936  
1          1129.0       463.0         1.8200  
2           333.0       117.0         1.6509  
3           515.0       226.0         3.1917  
4           624.0       262.0         1.9250  
...           ...         ...            ...  
19995      1258.0       607.0         1.1790  
19996      3496.0      1036.0         3.3906  
19997       693.0       220.0         2.2895  
19998        46.0        14.0         3.2708  
19999       753.0       260.0         8.5608  

[20000 rows x 8 columns]

In [9]:
from sklearn.preprocessing import StandardScaler
X_scale = StandardScaler()
y_scale = StandardScaler()

In [10]:
X = X_scale.fit_transform(unscaled_X)
y = y_scale.fit_transform(unscaled_y.values.reshape(-1, 1)).ravel()

In [11]:
X

array([[ 2.62341796, -0.67260797, -1.0831221 , ..., -0.36299762,
        -0.07210901, -1.25165577],
       [ 2.54356006, -0.57429739, -0.76520547, ..., -0.26220367,
        -0.0956865 , -1.07989419],
       [ 2.49863999, -0.90668077, -0.92416378, ..., -0.96599304,
        -1.00211012, -1.16887974],
       ...,
       [-0.06679515,  0.31517926, -1.48051789, ..., -0.64769634,
        -0.73227881, -0.83282905],
       [ 1.22091354, -0.71474107,  0.90385686, ..., -1.21974624,
        -1.27194143, -0.31643922],
       [-0.03185731, -0.56493448,  1.06281518, ..., -0.59464689,
        -0.62748996,  2.46731925]])

In [12]:
y

array([-1.21313424, -1.0989021 , -1.05043998, ..., -1.2555386 ,
       -0.38581661,  2.53490022])

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [14]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [15]:
prediction = model.predict(X_test)

In [23]:
prediction

array([-1.76371001,  0.04357012,  0.61464166, ..., -1.41893719,
       -0.23488623, -0.27926198])

In [19]:
scaled_prediction = y_scale.inverse_transform(prediction.reshape(-1, 1)).ravel()

In [20]:
scaled_prediction

array([  3278.67570243, 212117.42580477, 278107.12133234, ...,
        43118.61232097, 179940.63355204, 174812.83074308])

In [25]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_scale.inverse_transform(y_test.reshape(-1, 1)).ravel(), scaled_prediction)

4804056678.440655

In [26]:
mean_squared_error(y_scale.inverse_transform(y_test.reshape(-1, 1)).ravel(), scaled_prediction) ** 0.5

69311.30267453249